displayName=BA Healer Order
author=Thyler
support=
description=Displays Barbarian Assault Penance Healer spawn order and, optionally, food counts.
tags=barbarian assault,ba,healer,penance,barb assault
plugins=com.bahealerorder.BaHealerOrderPlugin
version=1.0.0
build=standard